# Stage 1: build app
FROM golang:1.23.4 AS builder

# Install lib
RUN apt-get update && \
    apt install -y --no-install-recommends \
    libaio1 \
    make \
    unzip && \ 
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Copy instantclient-basic-linux.x64 into container
COPY ./src/resources/oracle /oracle/

# Unzip lib oracle
RUN unzip /oracle/instantclient-basic-linux*.zip -d /oracle && \
    rm /oracle/instantclient-basic-linux*.zip

# Set environment for running oracle
ENV LD_LIBRARY_PATH=/oracle/instantclient_12_2 \
    ORACLE_HOME=/oracle/instantclient_12_2 \
    CGO_ENABLED=1

# Copy pkg app and download
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Using make file to install
RUN make swag_install && \
    make swag_gen && \
    make build

# Stage 2: run app
FROM ubuntu:22.04

# Run non-interactive
ARG DEBIAN_FRONTEND=noninteractive

# Set timezone
ENV TZ=Asia/Ho_Chi_Minh

# Install Lib oracle and Timezone
RUN apt-get update && \
    apt install -y --no-install-recommends \
    ca-certificates \
    curl \
    libaio1 \
    tzdata && \
    echo "$TZ" > /etc/timezone && \
    ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/*

# Copy lib oracle was install in builder
COPY --from=builder /oracle /oracle

WORKDIR /app

# Set env oracle
ENV LD_LIBRARY_PATH=/oracle/instantclient_12_2 \
    ORACLE_HOME=/oracle/instantclient_12_2 \
    CGO_ENABLED=1

# Copy source app
COPY --from=builder /build/src/resources ./src/resources
COPY --from=builder /build/gobe ./

ENTRYPOINT [ "./gobe" ]
